package com.autowash.backend.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.UUID;

/**
 * Maps to table `booking_slots`. Rows are pre-generated by
 * fn_generate_slots() (SlotGeneratorJob, B13) - Java code only ever reads
 * and (via the trg_slot_count trigger, never directly) updates booked_count.
 */
@Entity
@Table(name = "booking_slots")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BookingSlot {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "slot_date", nullable = false)
    private LocalDate slotDate;

    @Column(name = "slot_start", nullable = false)
    private LocalTime slotStart;

    @Column(name = "slot_end", nullable = false)
    private LocalTime slotEnd;

    @Column(name = "capacity", nullable = false)
    @Builder.Default
    private Integer capacity = 3;

    /**
     * Maintained by the DB trigger trg_slot_count - Java should treat this as
     * read-mostly (only ever mutated indirectly by inserting/cancelling a
     * booking, never written directly by application code).
     */
    @Column(name = "booked_count", nullable = false)
    @Builder.Default
    private Integer bookedCount = 0;

    @Column(name = "is_blocked", nullable = false)
    @Builder.Default
    private boolean blocked = false;

    @Transient
    public int getRemaining() {
        return capacity - bookedCount;
    }
}
